openapi: 3.0.0
info:
  title: Scissor URL Shortener API
  description: API documentation for Scissor URL Shortener.
  version: 1.0.0
paths:
 components:
     securitySchemes:
       bearerAuth:
         type: http
         scheme: bearer
         bearerFormat: JWT
     schemas:
       ShortenUrl:
         type: object
         required:
           - originalUrl
         properties:
           originalUrl:
             type: string
             description: The original URL to be shortened
           customUrl:
             type: string
             description: Custom alias for the shortened URL
         example:
           originalUrl: 'https://example.com'
           customUrl: 'customAlias'
 
  /api/shorten:
    post:
      summary: Shorten a URL
      requestBody:
        description: URL to be shortened
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                originalUrl:
                  type: string
                customUrl:
                  type: string
                  
      responses:
        '201':
          description: URL shortened successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortUrl:
                    type: string
        '400':
          description: Invalid URL
        '500':
          description: Server error
          
 /api/{code}/analytics:
     get:
       summary: Get analytics for a shortened URL
       tags: [URLs]
       security:
         - bearerAuth: []
       parameters:
         - in: path
           name: code
           schema:
             type: string
           required: true
           description: The code of the shortened URL
       responses:
         200:
           description: The analytics data
         404:
           description: URL not found
         500:
           description: Server error
           
   /api/user/urls:
     get:
       summary: Get all URLs created by the user
       tags: [URLs]
       security:
         - bearerAuth: []
       responses:
         200:
           description: A list of URLs created by the user
         401:
           description: Unauthorized access
         500:
           description: Server error
           
  /{code}:
     get:
       summary: Redirect to the original URL
       tags: [URLs]
       parameters:
         - in: path
           name: code
           schema:
             type: string
           required: true
           description: The code of the shortened URL
       responses:
         302:
          description: Redirects to the original URL
         404:
           description: URL not found
         500:
           description: Server error
      